# Generate color with matugen at first time
exec-once = matugen image ~/Pictures/Wallpapers/girl-with-lemon-tree.png -m dark && sleep 10 && sed -i '1,3d' ~/.config/hypr/hyprland/execs.conf

# Bar, wallpaper
exec-once = waybar
exec-once = swww-daemon
exec-once = swaync

# Polkit hyprland
exec-once = systemctl --user start hyprpolkitagent

# Nwg-stuff
exec-once = nwg-dock-hyprland -d -p bottom -mb 5 -nolauncher

# Clipboard: history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Input method
exec-once = fcitx5 -D

# Core components (authentication, lock screen, notification daemon)
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
exec-once = hyprpm reload

# Audio
exec-once = easyeffects --gapplication-service

# Clipboard

# Cursor
exec-once = hyprctl setcursor MacOS-Tahoe-Cursor 38
