# Mouse
bindm=SUPER,mouse:272,movewindow
bindm=SUPER,mouse:273,resizewindow

# Activity
bind=SUPER,Q,killactive

# Volume controller
binde = ,XF86AudioLowerVolume, exec, pactl -- set-sink-volume 0 -5%
binde = ,XF86AudioRaiseVolume, exec, pactl -- set-sink-volume 0 +5%
bind = ,XF86AudioMute, exec, pactl -- set-sink-mute 0 toggle
bind = ,XF86AudioMicMute, exec, pactl -- set-source-mute 0 toggle
binde = ,XF86MonBrightnessDown, exec, brightnessctl s 5%-
binde = ,XF86MonBrightnessUp, exec, brightnessctl s +5%

# Apps
bind=SUPER,RETURN,exec,alacritty
bind=SUPER+ALT,SLASH,exec,fuzzel
bind=SUPER,N,exec,swaync-client -t
bind=SUPER+ALT,O,exec,swaync-client -df && notify-send "Notification popup off and use SUPER+ALT+N to turn on"
bind=SUPER+ALT,I,exec,notify-send "Notification popup on and use SUPER+SHIFT+N to turn off" && swaync-client -dn
bind=SUPER+ALT,N,exec,swaync-client -df && notify-send "Cleared notification history and enabled notification popup" && swaync-client -C
bind=SUPER+SHIFT,E,exec,wlogout

# Clipboard
bind = Super, V, exec, pkill fuzzel || cliphist list | fuzzel  --match-mode fzf --dmenu | cliphist decode | wl-copy # Clipboard history >> clipboard
bind = Super+Shift, V, exec, pkill fuzzel || cliphist list | fuzzel  --match-mode fzf --dmenu | cliphist delete # Delete item in clipboard
bind = Super+Alt, V, exec, cliphist wipe && notify-send "Cleared clipboard history!"# Clear clipboard history

# Workspace
bind=SUPER,j,movefocus,d
bind=SUPER,k,movefocus,u

bind=SUPER,h,movefocus,l
bind=SUPER,l,movefocus,r

bind=SUPER,left,resizeactive,-40 0
bind=SUPER,right,resizeactive,40 0

bind=SUPER,up,resizeactive,0 -40
bind=SUPER,down,resizeactive,0 40

bind=SUPERSHIFT,h,movewindow,l
bind=SUPERSHIFT,l,movewindow,r
bind=SUPERSHIFT,k,movewindow,u
bind=SUPERSHIFT,j,movewindow,d

bind=SUPER,1,workspace,1
bind=SUPER,2,workspace,2
bind=SUPER,3,workspace,3
bind=SUPER,4,workspace,4
bind=SUPER,5,workspace,5
bind=SUPER,6,workspace,6
bind=SUPER,7,workspace,7
bind=SUPER,8,workspace,8
bind=SUPER,9,workspace,9
bind=SUPER,0,workspace,10

bind=SUPERSHIFT,1,movetoworkspacesilent,1
bind=SUPERSHIFT,2,movetoworkspacesilent,2
bind=SUPERSHIFT,3,movetoworkspacesilent,3
bind=SUPERSHIFT,4,movetoworkspacesilent,4
bind=SUPERSHIFT,5,movetoworkspacesilent,5
bind=SUPERSHIFT,6,movetoworkspacesilent,6
bind=SUPERSHIFT,7,movetoworkspacesilent,7
bind=SUPERSHIFT,8,movetoworkspacesilent,8
bind=SUPERSHIFT,9,movetoworkspacesilent,9
bind=SUPERSHIFT,0,movetoworkspacesilent,10
